app:
  max-word-length: ${MAX_WORD_LENGTH:7}
  manager-url: http://${MANAGER_HOST}:${MANAGER_PORT}

spring:
  application:
    name: worker
  jackson:
    time-zone: UTC

server:
  port: ${WORKER_PORT:8091}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:log4j2-plain.xml
