app:
  worker-value: 4

spring:
  application:
    name: worker
  jackson:
    time-zone: UTC

server:
  port: ${WORKER_PORT:8091}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:log4j2-plain.xml
