app:
  max-word-length: ${MAX_WORD_LENGTH:4}
  part-count: ${PART_COUNT:1}

spring:
  application:
    name: manager
  jackson:
    time-zone: UTC

server:
  port: ${MANAGER_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:log4j2-plain.xml
