app:
  part-count: ${PART_COUNT:1}
  worker-url: http://${WORKER_HOST}:${WORKER_PORT}
  timeout: ${TIMEOUT:60}
  alphabet: ${ALPHABET}

spring:
  application:
    name: manager
  jackson:
    time-zone: UTC

server:
  port: ${MANAGER_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:log4j2-plain.xml
