### POST crack
POST http://localhost:8090/api/hash/crack
Accept: application/json
Content-Type: application/json

{
    "hash":"e2fc714c4727ee9395f324cd2e7f331f",
    "maxLength": 4
}

### GET status
GET http://localhost:8090/api/hash/status?requestId=d9163e8b-cf0f-4b84-9f44-0d416522e3ac
Accept: application/json

### PATCH crack
PATCH http://localhost:8090/internal/api/manager/hash/crack/request
Accept: application/json
Content-Type: application/json

{
    "requestId": "320ae502-b84a-4d11-8f51-4722b8708f83",
    "data": ["hello", "world"]
}
